# This is the 1Password SSH agent config file, which allows you to customize the
# behavior of the SSH agent running on this machine.
#
# You can use it to:
# * Enable keys from other vaults than the Private vault
# * Control the order in which keys are offered to SSH servers
#
# EXAMPLE
#
# By default, all keys in your Private vault(s) are enabled:
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can enable more keys by adding more `[[ssh-keys]]` entries.
# For example, to first enable item "My SSH Key" from "My Custom Vault":
#
#  [[ssh-keys]]
#  item = "My SSH Key"
#  vault = "My Custom Vault"
#
#  [[ssh-keys]]
#  vault = "Private"
#
# You can test the result by running:
#
#  SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l
#
# More examples can be found here:
#  https://developer.1password.com/docs/ssh/agent/config

# Add the Deviceadmin Authentication key from my Administration vault
[[ssh-keys]]
item = "Server Authentication Key (Device Administrator)"
vault = "Administration"

# Add my Authenticaion key from my personal vault
[[ssh-keys]]
item = "Server Authentication Key (Andre Essing)"
vault = "Personal"

# Add my Git authentication key from my Personal vault
[[ssh-keys]]
item = "GitHub Authentication Key (Andre Essing)"
vault = "Personal"

[[ssh-keys]]
item = "GitHub Signing Key (Andre Essing)"
vault = "Personal"
