# ~/.config/starship.toml

# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Core behavior
add_newline = true                          # Blank line between prompts
command_timeout = 1000                      # Command timeout (ms)
scan_timeout = 30                           # File scan timeout (ms)
continuation_prompt = '[âˆ™](bright-black) '  # Multiline continuation marker

# Prompt layout (left)
format = """
$os\
$username\
$hostname\
$shell\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$jobs\
$cmd_duration\
$fill \
$all\
$kubernetes\
$helm\
$battery\
$line_break\
$character
"""

# OS indicator
[os]
disabled = false
format = '[$symbol]($style) '
style = 'bold white'

[os.symbols]
AIX = 'â¿'
Alpaquita = 'ğŸ””'
AlmaLinux = 'ïŒ'
Alpine = 'ïŒ€'
ALTLinux = 'â’¶'
Amazon = 'î­'
Android = 'îœ'
AOSC = 'ïŒ'
Arch = 'ó°£‡'
Artix = 'ïŒŸ'
Bluefin = 'ğŸŸ'
CachyOS = 'ğŸ—ï¸'
CentOS = 'ïŒ„'
Debian = 'î½'
DragonFly = 'î»¸'
Elementary = 'ïŒ‰'
Emscripten = 'ğŸ”—'
EndeavourOS = 'ïŒ¢'
Fedora = 'ïŒŠ'
FreeBSD = 'ïŠ'
Garuda = 'ïŒ·'
Gentoo = 'ïŒ'
HardenedBSD = 'ğŸ›¡ï¸'
Illumos = 'ïŒ¦'
Ios = 'ó°€·'
InstantOS = 'â²ï¸'
Kali = 'ïŒ§'
Linux = 'ï…¼'
Mabox = 'ğŸ“¦'
Macos = 'îœ‘'
Manjaro = 'ïŒ’'
Mariner = 'ğŸŒŠ'
MidnightBSD = 'ğŸŒ˜'
Mint = 'ïŒ'
NetBSD = 'ğŸš©'
NixOS = 'ïŒ“'
Nobara = 'ï€'
OpenBSD = 'ïŒ¨'
OpenCloudOS = 'â˜ï¸'
openEuler = 'ğŸ¦‰'
openSUSE = 'ïŒ”'
OracleLinux = 'î¡™'
PikaOS = 'ğŸ¤'
Pop = 'ïŒª'
Raspbian = 'ïŒ•'
RedHatEnterprise = 'ïŒ–'
Redhat = 'ïŒ–'
RockyLinux = 'ïŒ«'
Redox = 'ğŸ§ª'
Solus = 'ïŒ­'
SUSE = 'ïŒ”'
Ubuntu = 'ïŒ›'
Ultramarine = 'ğŸ”·'
Unknown = 'î¬²'
Uos = 'ğŸ²'
Void = 'ïŒ®'
Windows = 'î˜ª'
Zorin = 'ïŒ¯'

# Identity
[username]
disabled = false
format = '[$user]($style) '
show_always = true
style_user = 'bold 221'
style_root = 'bold 204'

[hostname]
disabled = false
format = 'on [$hostname]($style) '
ssh_only = false
style = 'bold 117'
trim_at = '.'

[shell]
disabled = false
bash_indicator = 'î¯Š'
zsh_indicator = 'î¯†'
powershell_indicator = 'î¯‡'
cmd_indicator = 'î¯„'
unknown_indicator = 'ï’‰'
format = 'in [$indicator]($style) '
style = '243'

# Location
[directory]
disabled = false
format = 'at [$path]($style) [$read_only]($read_only_style)'
home_symbol = '~'
read_only = 'ï€£ '
read_only_style = 'red'
style = 'bold 141'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = false


# Git
[git_branch]
disabled = false
symbol = 'îœ¥ '
format = 'on [$symbol$branch(:$remote_branch)]($style) '
truncation_length = 24
truncation_symbol = 'â€¦'
style = 'bold 150'
only_attached = false
ignore_bare_repo = false

[git_commit]
disabled = false
format = '[\($hash$tag\)]($style) '
style = '150'
only_detached = true 
tag_disabled = true
tag_symbol = ' ï€« '
commit_hash_length = 7
tag_max_candidates = 0

[git_state]
disabled = false
format = '[\($state( $progress_current/$progress_total)\)]($style) '
rebase = 'REBASING'
merge ='MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold 221'

[git_metrics]
disabled = false
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style = 'dimmed 150'
deleted_style = 'dimmed 204'
only_nonzero_diffs = true

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold 204'
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
deleted = 'âœ˜'
diverged = 'â‡• â‡¡${ahead_count} â‡£${behind_count}'
conflicted = '='
modified = '!'
renamed = 'Â»'
staged = '[+\($count\)](050)'
stashed = '\$'
typechanged = ''
untracked = '?'
up_to_date = ''


# Jobs & timing
[jobs]
disabled = false
format = '[$symbol$number]($style) '
symbol = 'î«¸ '
style = 'bold 243'
symbol_threshold = 1
number_threshold = 2

[cmd_duration]
disabled = false
min_time = 500
format = '[ï”  $duration]($style) '
style = 'italic 243'


# Cloud
[aws]
disabled = false
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style) | '
symbol = 'î­ '
style = 'bold 208'

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) | '
symbol = 'ó° … '
style = 'bold 117'

[gcloud]
disabled = false
format = 'on [$symbol$account(@$domain)(\($region\))]($style) | '
symbol = 'ó±‡¶ '
style = 'bold 204'


# Runtimes & packages
[dotnet]
disabled = false
format = '[$symbol($version)(ó°£‰ $tfm)]($style) | '
heuristic = true
style = 'bold 209'
symbol = 'î¿ '
version_format = 'v${raw}'

[golang]
disabled = false
format = '[$symbol($version)]($style) | '
version_format = 'v${raw}'
symbol = 'ó°Ÿ“ '
style = 'bold 209'
not_capable_style = 'bold red'

[nodejs]
disabled = false
format = '[$symbol($version)]($style) | '
style = 'bold 209'
not_capable_style = 'bold red'
symbol = 'î´ '
version_format = 'v${raw}'

[package]
disabled = false
display_private = false
format = '[$symbol$version]($style) | '
style = 'bold 209'
symbol = 'ó°– '
version_format = 'v${raw}'

[python]
disabled = false
format = '[$symbol${pyenv_prefix}(${version})( \($virtualenv\))]($style) | '
version_format = 'v${raw}'
symbol = 'î˜† '
style = 'bold 209'
pyenv_version_name = false


# Kubernetes & Helm
[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) | '
style = 'bold 117'
symbol = 'î  '

[helm]
disabled = false
format = '[$symbol($version)]($style) | '
style = 'bold 117'
symbol = 'îŸ» '
version_format = 'v${raw}'


# Battery
[battery]
disabled = false
format = '[$symbol$percentage]($style)'
charging_symbol = 'ó°‚„ '
discharging_symbol = 'ó±Ÿ '
empty_symbol = 'ó°‚ '
full_symbol = 'ó°¹ '
unknown_symbol = 'ó°‚‘ '

[[battery.display]]
style = 'bold 204'
threshold = 10

[[battery.display]]
style = 'bold 221'
threshold = 30

[[battery.display]]
style = 'bold 150'
threshold = 100


# Prompt separators
[fill]
disabled = false
symbol = ' '
style = ''

[line_break]
disabled = false


# Prompt character
[character]
disabled = false
format = '$symbol '
error_symbol = '[âœ•](bold 204)'
success_symbol = '[âœ](bold 150)'
vimcmd_symbol = '[](bold 141)'
vimcmd_replace_one_symbol = '[](bold 141)'
vimcmd_replace_symbol = '[](bold 141)'
vimcmd_visual_symbol = '[](bold 221)'
